### ISSUE TITLE
Capítulo 7: Inyección de Dependencias

### ISSUE THREAD

**Issue by wilsenhc** [wilsenhc/php-the-right-way#14]
## Capítulo 7: Inyección de Dependencias
- [x] 06-01-01-Dependency-Injection.md - **Asignado a:** @vicmans
- [x] 06-02-01-Basic-Concept.md - **Asignado a:** @vicmans
- [x] 06-03-01-Complex-Problem.md - **Asignado a:** @vicmans
- [x] 06-04-01-Containers.md - **Asignado a:** @vicmans
- [x] 06-05-01-Further-Reading.md - **Asignado a:** @vicmans

**Comment by vicmans** [comment]
No hubo modificación en la sección `06-05-01-Further-Reading` se mantienen los mismos enlaces para Lecturas adicionales
