### ISSUE TITLE
Capítulo 9: Plantillas

### ISSUE THREAD

**Issue by wilsenhc** [wilsenhc/php-the-right-way#16]
## Capítulo 9: Plantillas
- [x] 08-01-01-Templating.md - **Asignado a:** @vicmans
- [x] 08-02-01-Benefits.md - **Asignado a:** @vicmans
- [x] 08-03-01-Plain-PHP-Templates.md - **Asignado a:** @vicmans
- [x] 08-04-01-Compiled-Templates.md - **Asignado a:** @vicmans
- [x] 08-05-01-Further-Reading.md - **Asignado a:** @vicmans

**Comment by vicmans** [comment]
Voy con este capitulo
