### ISSUE TITLE
Capítulo 10: Errores y Excepciones

### ISSUE THREAD

**Issue by wilsenhc** [wilsenhc/php-the-right-way#17]
## Capítulo 10: Errores y Excepciones
- [x] 09-01-01-Errors-and-Exceptions.md - **Asignado a:** @paulohbsousa
- [x] 09-02-01-Errors.md - **Asignado a:** @paulohbsousa 
- [x] 09-03-01-Exceptions.md - **Asignado a:** @paulohbsousa

**Comment by paulohbsousa** [comment]
I can take this one.

Puedo coger ese

**Comment by wilsenhc** [comment]
Gracias @paulohbsousa !
