### ISSUE TITLE
Capítulo 14: Virtualización

### ISSUE THREAD

**Issue by wilsenhc** [wilsenhc/php-the-right-way#21]
## Capítulo 14: Virtualización
- [x] 13-01-01-Virtualization.md - **Asignado a:** @abr4xas
- [x] 13-02-01-Vagrant.md - **Asignado a:** @abr4xas
- [x] 13-03-01-Docker.md - **Asignado a:** @abr4xas

**Comment by wilsenhc** [comment]
Asignado a @abr4xas

**Comment by abr4xas** [comment]
Ya esta listo estas traducciones! 😃
